### ISSUE TITLE
BACKUP: Feedback on summary grid in-scope

### ISSUE THREAD

**Issue by centiqbob** [Azure/AzureMonitorForSAPSolutions#75]
Collation of feedback on [Backup monitoring workbook ](https://go.microsoft.com/fwlink/?linkid=874159&resourceId=%2Fsubscriptions%2Fdb5f064b-73c2-4039-8262-f230cc64c659%2Fresourcegroups%2Fsapmon-rg-61164a47e45d81%2Fproviders%2Fmicrosoft.operationalinsights%2Fworkspaces%2Fxdm-law&featureName=Workbooks&itemId=%2Fsubscriptions%2Fdb5f064b-73c2-4039-8262-f230cc64c659%2Fresourcegroups%2Fsapmon-rg-61164a47e45d81%2Fproviders%2Fmicrosoft.insights%2Fworkbooks%2F9fdf4445-dc72-4d69-b869-d45b03c89124&workbookTemplateName=pre-release&func=NavigateToPortalFeature&type=workbook)

- [x] 1) Decrease the number of decimal places to 0 on ``[Age of status]``
- [x] 2) Change format of [Previous successful backup age] to same as ``[Age of Status]``
- [x] 3)  Change ``[Previous successful backup age]`` label to ``[Age of previous successful backup]``
- [x] 4)  Add a threshold render to the ``[Number of failed backups]`` that defaults to the info Icon, and blank if the content starts with a zero
- [x] 5)  Summary (Parent) values in the summary grid can just show "fail" if one of the backup type is failed, remove all other values from summary other than total count of failures.
- [x] 6) for "data snapshot", the last one failed - according to "number of failed backups", there must be one that was successful. yet, the "previous successful" column is empty?
 - [x] 7) for threshold renderers, i generally prefer to just have the symbol (check or "X") instead of adding "Success" or "Fail" (you can achieve that by leaving the "text" field in the renderer's settings empty)
 - [x] 8) Change column label "Last Status" to "Backup status"
 - [x] 9) Change column label "Age of Status to "Backup Age"

**Comment by xmanningcentiq** [comment]
All items checked off, ready for review.
