### ISSUE TITLE
setup/configureMonitorVM.sh hangs when run because apt-get is waiting for user input

### ISSUE THREAD

**Issue by xmanningcentiq** [Azure/AzureMonitorForSAPSolutions#86]
[sapmon/setup/configureMonitorVM.sh](https://github.com/Azure/AzureMonitorForSAPSolutions/blob/6fa91e757a4f2fdd490c8a9c792c54edb435386a/sapmon/setup/configureMonitorVM.sh#L37) at 6fa91e will hang because it is waiting for user input on `apt-get` on line 37

```bash
# Install PyODBC dependencies
ExecuteCommand "apt-get install g++ unixodbc-dev"
```

It should be:

```bash
# Install PyODBC dependencies
ExecuteCommand "apt-get install -y g++ unixodbc-dev"
```

**Comment by persiaAziz** [comment]
This is fixed
