### ISSUE TITLE
Additional chart for local vs shipped log data rates

### ISSUE THREAD

**Issue by centiqbob** [Azure/AzureMonitorForSAPSolutions#91]
Create Line graph for the following 2 metrics:

`Local log buffer   write throughput (MB/s) = SHIPPED_LOG_BUFFERS_SIZE / SHIPPED_LOG_BUFFERS_DURATION`

`Log buffer shipping throughput (MB/s) =TOTAL_WRITE_SIZE / TOTAL_WRITE_TIME`

**Comment by centiqbob** [comment]
The sql from the mini-checks returns the following for the test tenant HN2

SITEA -> SITEC
Metric | value
-- | --
Local   log buffer write throughput (MB/s) | 15.35
Local log buffer write   throughput (MB/s) | 15.35
Log buffer shipping throughput   (MB/s) | 36.42
Log buffer shipping throughput   (MB/s) | 36.42

SITEA -> SITEB
Metric | value
-- | --
Local   log buffer write throughput (MB/s) | 15.35
Local log buffer write   throughput (MB/s) | 15.35
Log buffer shipping throughput   (MB/s) | 5
Log buffer shipping throughput   (MB/s) | 5

**Comment by xmanningcentiq** [comment]
SITEA -> SITEC (indexserver)

![Screenshot from 2020-06-25 11-27-03](https://user-images.githubusercontent.com/26088560/85702975-d28e0200-b6d6-11ea-83d0-1942e7051e67.png)

SITEA -> SITEB (indexserver)

![Screenshot from 2020-06-25 11-26-46](https://user-images.githubusercontent.com/26088560/85702985-d588f280-b6d6-11ea-9cac-faaeec7c6f61.png)
