### ISSUE TITLE
HSR: Feedback on live-data workbook

### ISSUE THREAD

**Issue by xmanningcentiq** [Azure/AzureMonitorForSAPSolutions#92]
Feedback received on workbook using live data:

1. [x] Sync status refers to the the relationship between two nodes to probably should be on the arc line (aka the edge). This can be added to the arc line with an emoji (eg. [check mark button](https://emojipedia.org/check-mark-button/) and [cross mark button](https://emojipedia.org/cross-mark-button/))
1. [x] Graph object is best collapsed in a group by default with an option to expand.
1. [x] Make graph object "full" size
1. [x] Graph object should show the state according to the last data collected.
1. [x] Graph object should sit above timeframe selector as it will not be affected by this.
1. [x] Summary tree should have the latest recorded state, however for "seconds behind master" and "async log buffer" we could do a "now (max)" style value or "now (avg)" (also needs to be clear in the columns). Spark graphs can support this.
1. [x] Try colour coding for node
1. [ ] Try edge size to be driven by log-ship rate
1. [x] concatenate the Replication mode and operation mode and detailed status into a single column to save space in the summary from mostly empty columns

**Comment by centiqbob** [comment]
Can't get the edge-size to work and on reflection, I assume that it would draw each line a relative size to the others, so might not be that useful. So will not bother pursuing this idea further.
